version: '3.4'

networks:
  app:
    driver: bridge

services:
  postgres-mklf:
    container_name: postgres-mklf
    image: postgres:14.7
    hostname: postgres-mklf
    networks:
      app:
        aliases:
          - postgres-mklf
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always

  redis-mklf:
    container_name: redis-mklf
    hostname: redis-mklf
    image: 'redis'
    command: redis-server --save 20 1 --loglevel warning --requirepass password123
    ports:
      - '6379:6379'
    volumes:
      - './data/redis_data:/data'
    networks:
      app:
        aliases:
          - redis-mklf

  nginx-mklf:
    image: nginx:latest
    container_name: nginx-mklf
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-mklf
    networks:
      - app


  api-mklf:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: api-mklf
    hostname: api-mklf
    volumes:
      - ../:/var/www/
    networks:
      - app
