version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    depends_on:
      - sonar-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonarqubedb
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs/:/opt/sonarqube/logs
    ports:
      - "9900:9000"
  sonar-db:
    container_name: sonar_db
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqubedb
    volumes:
      - ./sonar-db/:/var/lib/postgresql
      - ./sonar-db/data:/var/lib/postgresql/data
